global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:9464"]
  - job_name: "gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["gateway:8000"]
  - job_name: "retrieval"
    metrics_path: /metrics
    static_configs:
      - targets: ["retrieval:8002"]
  - job_name: "orchestrator"
    metrics_path: /metrics
    static_configs:
      - targets: ["orchestrator:8003"]
